services:
  - docker

language: generic

env:
- DISTRI=ubuntu DESKTOP=xfce
- DISTRI=ubuntu DESKTOP=icewm
- DISTRI=centos DESKTOP=xfce
- DISTRI=centos DESKTOP=icewm

script:
  - docker build -t moderras/docker-headless-vnc:${DISTRI}-${DESKTOP} -f ./Dockerfile.${DISTRI}.${DESKTOP}.vnc .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push moderras/docker-headless-vnc:${DISTRI}-${DESKTOP}

## use standard notification to committer
#notifications:
#    recipients:
#      - "testautomatisierung@consol.de"
#    on_success: change # default: change
#    on_failure: always # default: always
